### ISSUE TITLE
Exception on power on

### ISSUE THREAD

**Issue by JunaidQuickFuel** [aaltynbek/pda_rfid_scanner#1]
java.io.FileNotFoundException: /proc/gpiocontrol/set_uhf (No such file or directory)
W/System.err(11128): 	at java.io.FileOutputStream.open0(Native Method)
W/System.err(11128): 	at java.io.FileOutputStream.open(FileOutputStream.java:287)
W/System.err(11128): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
W/System.err(11128): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
W/System.err(11128): 	at java.io.FileWriter.<init>(FileWriter.java:63)
W/System.err(11128): 	at com.pda_rfid_scanner.utils.PowerUtil.power(PowerUtil.java:12)
W/System.err(11128): 	at com.pda_rfid_scanner.utils.LFUtil.powerOn(LFUtil.java:85)
W/System.err(11128): 	at com.pda_rfid_scanner.PdaRfidScannerPlugin.onMethodCall(PdaRfidScannerPlugin.java:64)
W/System.err(11128): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(11128): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(11128): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/System.err(11128): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(11128): 	at android.os.Handler.handleCallback(Handler.java:790)
W/System.err(11128): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(11128): 	at android.os.Looper.loop(Looper.java:164)
W/System.err(11128): 	at android.app.ActivityThread.main(ActivityThread.java:6548)
W/System.err(11128): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11128): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err(11128): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
W/System.err(11128): java.io.IOException: Cannot run program "/system/bin/su": error=2, No such file or directory
W/System.err(11128): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
W/System.err(11128): 	at java.lang.Runtime.exec(Runtime.java:692)
W/System.err(11128): 	at java.lang.Runtime.exec(Runtime.java:525)
W/System.err(11128): 	at java.lang.Runtime.exec(Runtime.java:422)
W/System.err(11128): 	at android_serialport_api.SerialPort.<init>(SerialPort.java:47)
W/System.err(11128): 	at android_serialport_api.SerialPortTool.getSerialPort(SerialPortTool.java:53)
W/System.err(11128): 	at com.pda_rfid_scanner.utils.LFUtil.open(LFUtil.java:114)
W/System.err(11128): 	at com.pda_rfid_scanner.PdaRfidScannerPlugin.lfOpen(PdaRfidScannerPlugin.java:105)
W/System.err(11128): 	at com.pda_rfid_scanner.PdaRfidScannerPlugin.onMethodCall(PdaRfidScannerPlugin.java:65)
W/System.err(11128): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(11128): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(11128): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/System.err(11128): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(11128): 	at android.os.Handler.handleCallback(Handler.java:790)
W/System.err(11128): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(11128): 	at android.os.Looper.loop(Looper.java:164)
W/System.err(11128): 	at android.app.ActivityThread.main(ActivityThread.java:6548)
W/System.err(11128): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11128): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err(11128): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
W/System.err(11128): Caused by: java.io.IOException: error=2, No such file or directory
W/System.err(11128): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
W/System.err(11128): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
W/System.err(11128): 	at java.lang.ProcessImpl.start(ProcessImpl.java:128)
W/System.err(11128): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)

**Comment by aaltynbek** [comment]
Can check it now, with new version of this package
